### ISSUE TITLE
TypeError: 'NoneType' object is not iterable，但不影响使用

### ISSUE THREAD

**Issue by RJCooLEST** [zyujs/hoshino_training#1]
[2020-11-03 19:40:24,232 nonebot] INFO: Scheduler started
[hoshino_training] load module anti-holo failed
Traceback (most recent call last):
  File "/root/pcrbot/HoshinoBot/hoshino/modules/hoshino_training/training.py", line 20, in load_functions
    importlib.import_module('hoshino.modules.hoshino_training.functions.' + name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/pcrbot/HoshinoBot/hoshino/modules/hoshino_training/functions/anti-holo.py", line 48, in <module>
    keyword_replace(SB_HOLO, anti_holo)
  File "/root/pcrbot/HoshinoBot/hoshino/modules/hoshino_training/util/keyword.py", line 5, in keyword_replace
    for keyword in keyword_list:
TypeError: 'NoneType' object is not iterable
[hoshino_training] load module comic successed
[hoshino_training] load module chara successed
[hoshino_training] load module query successed
[hoshino_training] load module util successed
[2020-11-03 19:40:24,320 anti-concurrency] INFO: Scheduled job add_trigger_words_wrapper_job start.
[2020-11-03 19:40:24,321 anti-concurrency] INFO: Scheduled job add_trigger_words_wrapper_job completed.

是否能通过升级最新的 Hoshino 的框架解决。

**Comment by zyujs** [comment]
已修正
