### ISSUE TITLE
 rank_online功能无法正常加载

### ISSUE THREAD

**Issue by shadow7755** [zyujs/hoshino_training#2]
hoshino报错日志
[hoshino_training] load module rank_online failed
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\modules\hoshino_training\training.py", line 20, in load_functions
    importlib.import_module('hoshino.modules.hoshino_training.functions.' + name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\modules\hoshino_training\functions\rank_online.py", line 115, in <module>
    rex_replace(r'^(\*?([日台国陆b])服?([前中后]*)卫?)?rank(表|推荐|指南)?$', rank_sheet, r'^(\*?([日台国陆bxfwy])服?([ 前中后]*)卫?)?rank(表|推荐|指南)?$')
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\modules\hoshino_training\util\rex.py", line 10, in rex_replace
    rex.allrex[k].func = func
AttributeError: 'list' object has no attribute 'func'

**Comment by zyujs** [comment]
我觉得是你的hoshino版本太老了

**Comment by shadow7755** [comment]
我今天从git pull上已经拉的是最新版的hoshino了啊，是最新版的报的这个错

**Comment by shadow7755** [comment]
前几天更新 hoshino/trigger.py 这个文件的内容修改过，是不是和这个有关系

**Comment by zyujs** [comment]
看了一下, 是hoshino最近改了代码, 回头我更新一下插件.
